/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/components/layout/logo/AppLogo.vue')['default']
    AppMenu: typeof import('./src/components/layout/menu/AppMenu.vue')['default']
    AppTopBar: typeof import('./src/components/layout/topbar/AppTopBar.vue')['default']
    AppWorkTab: typeof import('./src/components/layout/worktab/AppWorkTab.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    EZSvgIcon: typeof import('./src/components/icons/EZSvgIcon.vue')['default']
    LoginPage: typeof import('./src/views/login/LoginPage.vue')['default']
    MenuForm: typeof import('./src/views/system/menu/MenuForm.vue')['default']
    MenuManagementPage: typeof import('./src/views/system/menu/MenuManagementPage.vue')['default']
    MyLayout: typeof import('./src/components/layout/MyLayout.vue')['default']
    NotFountPage: typeof import('./src/views/errors/NotFountPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubMenu: typeof import('./src/components/layout/menu/SubMenu.vue')['default']
    WorkbenchPage: typeof import('./src/views/dashboard/WorkbenchPage.vue')['default']
  }
}
